version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install gcloud CLI
          command: |
            echo $key_gcp > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud config set project zalora_dwh
      - run:
          name: Check for Changes
          command: |
            CHANGED_FILES=$(git diff --name-only $CIRCLE_BRANCH main)
            for FILE in $CHANGED_FILES; do
              bq query --use_legacy_sql=false --nouse_legacy_sql --project_id=$GCLOUD_PROJECT_ID < $FILE
            done
workflows:
  version: 2
  build-deploy:
    jobs:
      - build