version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install gcloud CLI
          command: |
            echo $GCLOUD_SERVICE_KEY > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud config set project $GCLOUD_PROJECT_ID
      - run:
          name: Check for Changes
          command: |
            CHANGED_FILES=$(git diff --name-only $CIRCLE_BRANCH $REFERENCE_BRANCH)
            for FILE in $CHANGED_FILES; do
              if [[ $FILE == "your-ddl-script.sql" ]]; then
                bq query --use_legacy_sql=false --nouse_legacy_sql --project_id=$GCLOUD_PROJECT_ID < $FILE
              fi
            done
workflows:
  version: 2
  build-deploy:
    jobs:
      - build