version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install gcloud CLI
          command: |
            echo $key_gcp > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud config set project zalora-dwh
      - run:
          name: List All Files
          paths:
          - 'ddl/**'
          command: |
            ALL_FILES=$(git ls-tree --full-tree --name-only $CIRCLE_BRANCH)
            echo "All files:"
            echo "$ALL_FILES"
      - run:
          name: Debug Git
          command: |
            echo "CIRCLE_BRANCH: $CIRCLE_BRANCH"
            CHANGED_FILES=$(git diff --name-only $CIRCLE_BRANCH)
            echo "CHANGED_FILES: $CHANGED_FILES"
      - run:
          name: Check for Changes
          command: |
            #bq query --use_legacy_sql=false --nouse_legacy_sql --project_id=zalora-dwh < table1.sql
            CHANGED_FILES=$(git diff --name-only $CIRCLE_BRANCH)
            echo  $CHANGED_FILES
            for FILE in $CHANGED_FILES; do
              SQL=`cat $FILE`
              echo $SQL
              bq query --use_legacy_sql=false --nouse_legacy_sql --project_id=zalora-dwh < $FILE
            done
workflows:
  version: 2
  build-deploy:
    jobs:
      - build